### ISSUE TITLE
Installation issues with ruby 2.7.1, OS X Big Sur & xcode 13.1

### ISSUE THREAD

**Issue by StefanWallin** [tenderlove/dnssd#28]
### Description
I'm having issues installing this gem on Big Sur under ruby 2.7.1. It seems by this traceback that it can't find the file `/usr/lib/libmdns.dylib` which does indeed not exist. I cannot find any brew-package that would supplement this dependency for me.

### Versions
```
xcode-select version 2384.
xcode version 13.1
xcode command line tools version: 13A1030d
Mac os Version: macOS Big Sur 11.6 (20G165)
Mac arch: Intel
Ruby v: 2.7.1
Bundler v: 2.1.4
```

### Edited — Reproduced on
```
Mac arch: Intel
ruby 2.6.2p47 (2019-03-13 revision 67232) [x86_64-darwin19]
Bundler version 1.17.2
xcode-select version 2384
macOS Big Sur 11.6
```

### Steps to reproduce
```
  rails new experiment
  cd experiment
  bundle exec rails serve # this works
  bundle add dnssd
  bundle exec rails serve # this crashes with traceback
```

I've reproduced this on two separate macbook pro's. Both Intel, not sure that the exact versions are the same on both.

**Example repo:**
https://github.com/StefanWallin/dnssd-install-issuse

### Traceback
```
Traceback (most recent call last):
	43: from bin/rails:4:in `<main>'
	42: from /Users/username/.asdf/installs/ruby/2.7.1/lib/ruby/gems/2.7.0/gems/bootsnap-1.7.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
	41: from /Users/username/.asdf/installs/ruby/2.7.1/lib/ruby/gems/2.7.0/gems/bootsnap-1.7.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
	40: from /Users/username/.asdf/installs/ruby/2.7.1/lib/ruby/gems/2.7.0/gems/bootsnap-1.7.2/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
	39: from /Users/username/.asdf/installs/ruby/2.7.1/lib/ruby/gems/2.7.0/gems/bootsnap-1.7.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
	38: from /Users/username/.asdf/installs/ruby/2.7.1/lib/ruby/gems/2.7.0/gems/bootsnap-1.7.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
	37: from /Users/username/.asdf/installs/ruby/2.7.1/lib/ruby/gems/2.7.0/gems/railties-6.1.3/lib/rails/commands.rb:18:in `<main>'
	36: from /Users/username/.asdf/installs/ruby/2.7.1/lib/ruby/gems/2.7.0/gems/railties-6.1.3/lib/rails/command.rb:50:in `invoke'
	35: from /Users/username/.asdf/installs/ruby/2.7.1/lib/ruby/gems/2.7.0/gems/railties-6.1.3/lib/rails/command/base.rb:69:in `perform'
	34: from /Users/username/.asdf/installs/ruby/2.7.1/lib/ruby/gems/2.7.0/gems/thor-1.1.0/lib/thor.rb:392:in `dispatch'
	33: from /Users/username/.asdf/installs/ruby/2.7.1/lib/ruby/gems/2.7.0/gems/thor-1.1.0/lib/thor/invocation.rb:127:in `invoke_command'
	32: from /Users/username/.asdf/installs/ruby/2.7.1/lib/ruby/gems/2.7.0/gems/thor-1.1.0/lib/thor/command.rb:27:in `run'
	31: from /Users/username/.asdf/installs/ruby/2.7.1/lib/ruby/gems/2.7.0/gems/railties-6.1.3/lib/rails/commands/server/server_command.rb:135:in `perform'
	30: from /Users/username/.asdf/installs/ruby/2.7.1/lib/ruby/gems/2.7.0/gems/railties-6.1.3/lib/rails/commands/server/server_command.rb:135:in `tap'
	29: from /Users/username/.asdf/installs/ruby/2.7.1/lib/ruby/gems/2.7.0/gems/railties-6.1.3/lib/rails/commands/server/server_command.rb:138:in `block in perform'
	28: from /Users/username/.asdf/installs/ruby/2.7.1/lib/ruby/gems/2.7.0/gems/activesupport-6.1.3/lib/active_support/dependencies.rb:332:in `require'
	27: from /Users/username/.asdf/installs/ruby/2.7.1/lib/ruby/gems/2.7.0/gems/activesupport-6.1.3/lib/active_support/dependencies.rb:299:in `load_dependency'
	26: from /Users/username/.asdf/installs/ruby/2.7.1/lib/ruby/gems/2.7.0/gems/activesupport-6.1.3/lib/active_support/dependencies.rb:332:in `block in require'
	25: from /Users/username/.asdf/installs/ruby/2.7.1/lib/ruby/gems/2.7.0/gems/bootsnap-1.7.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
	24: from /Users/username/.asdf/installs/ruby/2.7.1/lib/ruby/gems/2.7.0/gems/bootsnap-1.7.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
	23: from /Users/username/.asdf/installs/ruby/2.7.1/lib/ruby/gems/2.7.0/gems/bootsnap-1.7.2/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
	22: from /Users/username/.asdf/installs/ruby/2.7.1/lib/ruby/gems/2.7.0/gems/bootsnap-1.7.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
	21: from /Users/username/.asdf/installs/ruby/2.7.1/lib/ruby/gems/2.7.0/gems/bootsnap-1.7.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
	20: from /Users/username/gitstuff/experiment/config/application.rb:7:in `<main>'
	19: from /Users/username/.asdf/installs/ruby/2.7.1/lib/ruby/2.7.0/bundler.rb:174:in `require'
	18: from /Users/username/.asdf/installs/ruby/2.7.1/lib/ruby/2.7.0/bundler/runtime.rb:58:in `require'
	17: from /Users/username/.asdf/installs/ruby/2.7.1/lib/ruby/2.7.0/bundler/runtime.rb:58:in `each'
	16: from /Users/username/.asdf/installs/ruby/2.7.1/lib/ruby/2.7.0/bundler/runtime.rb:69:in `block in require'
	15: from /Users/username/.asdf/installs/ruby/2.7.1/lib/ruby/2.7.0/bundler/runtime.rb:69:in `each'
	14: from /Users/username/.asdf/installs/ruby/2.7.1/lib/ruby/2.7.0/bundler/runtime.rb:74:in `block (2 levels) in require'
	13: from /Users/username/.asdf/installs/ruby/2.7.1/lib/ruby/gems/2.7.0/gems/bootsnap-1.7.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
	12: from /Users/username/.asdf/installs/ruby/2.7.1/lib/ruby/gems/2.7.0/gems/bootsnap-1.7.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
	11: from /Users/username/.asdf/installs/ruby/2.7.1/lib/ruby/gems/2.7.0/gems/bootsnap-1.7.2/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
	10: from /Users/username/.asdf/installs/ruby/2.7.1/lib/ruby/gems/2.7.0/gems/bootsnap-1.7.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
	 9: from /Users/username/.asdf/installs/ruby/2.7.1/lib/ruby/gems/2.7.0/gems/bootsnap-1.7.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
	 8: from /Users/username/.asdf/installs/ruby/2.7.1/lib/ruby/gems/2.7.0/gems/dnssd-3.0.1/lib/dnssd.rb:167:in `<main>'
	 7: from /Users/username/.asdf/installs/ruby/2.7.1/lib/ruby/gems/2.7.0/gems/activesupport-6.1.3/lib/active_support/dependencies.rb:332:in `require'
	 6: from /Users/username/.asdf/installs/ruby/2.7.1/lib/ruby/gems/2.7.0/gems/activesupport-6.1.3/lib/active_support/dependencies.rb:299:in `load_dependency'
	 5: from /Users/username/.asdf/installs/ruby/2.7.1/lib/ruby/gems/2.7.0/gems/activesupport-6.1.3/lib/active_support/dependencies.rb:332:in `block in require'
	 4: from /Users/username/.asdf/installs/ruby/2.7.1/lib/ruby/gems/2.7.0/gems/bootsnap-1.7.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
	 3: from /Users/username/.asdf/installs/ruby/2.7.1/lib/ruby/gems/2.7.0/gems/bootsnap-1.7.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
	 2: from /Users/username/.asdf/installs/ruby/2.7.1/lib/ruby/gems/2.7.0/gems/bootsnap-1.7.2/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
	 1: from /Users/username/.asdf/installs/ruby/2.7.1/lib/ruby/gems/2.7.0/gems/bootsnap-1.7.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
/Users/username/.asdf/installs/ruby/2.7.1/lib/ruby/gems/2.7.0/gems/bootsnap-1.7.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require': dlopen(/Users/username/.asdf/installs/ruby/2.7.1/lib/ruby/gems/2.7.0/gems/dnssd-3.0.1/lib/dnssd/dnssd.bundle, 9): Library not loaded: /usr/lib/libmdns.dylib (LoadError)
  Referenced from: /Users/username/.asdf/installs/ruby/2.7.1/lib/ruby/gems/2.7.0/gems/dnssd-3.0.1/lib/dnssd/dnssd.bundle
  Reason: image not found - /Users/username/.asdf/installs/ruby/2.7.1/lib/ruby/gems/2.7.0/gems/dnssd-3.0.1/lib/dnssd/dnssd.bundle
```

**Comment by StefanWallin** [comment]
Upgrading to MacOS Monterey v 12.0.1 solved this issue for me. Even though the file is not available at `/usr/lib/libmdns.dylib` in Monterey.
